server:
    port: 8001
    error:
        include-message: always
        include-binding-errors: always
spring:
    data:
        redis:
            refresh-token-db:
                port: 6379
                host: localhost
            registration-db:
                port: 6380
                host: localhost
    datasource:
        url: ${AUTH_MANAGEMENT_SERVICE_DATABASE_URL}
        username: ${AUTH_MANAGEMENT_SERVICE_DATABASE_USERNAME}
        password: ${AUTH_MANAGEMENT_SERVICE_DATABASE_PASSWORD}
        driver-class-name: org.postgresql.Driver
    jpa:
        database: postgresql
        open-in-view: false
        show-sql: true
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
            jakarta:
                persistence:
                    sharedCache:
                        mode: ENABLE_SELECTIVE
    mail:
        host: smtp.yandex.ru
        port: 465
        username: ${AUTH_MANAGEMENT_SERVICE_MAIL_USERNAME}
        password: ${AUTH_MANAGEMENT_SERVICE_MAIL_PASSWORD}
        protocol: smtps
        default-encoding: UTF-8
rednet:
    app:
        password-encoder-strength: 10
        access-token-cookie-name: rednet-access-token
        access-token-expiration-ms: 60000
        access-token-cookie-expiration-s: 60
        access-token-cookie-path: /
        access-token-secret-key: ${AUTH_ACCESS_SECRET_KEY}
        registration-expiration-ms: 300000
        registration-token-activation-ms: 60000
        registration-token-cookie-name: rednet-reg-token
        registration-token-cookie-expiration-s: 300
        registration-token-secret-key: ${AUTH_REGISTRATION_SECRET_KEY}
        refresh-token-cookie-name: rednet-refresh-token
        refresh-token-expiration-ms: 172800000
        refresh-token-cookie-expiration-s: 172800
        refresh-token-cookie-path: /refresh-tokens
        refresh-token-secret-key: ${AUTH_REFRESH_SECRET_KEY}
        auth-token-issuer: rednet-auth